[build]
  base = "apps/excelidraw-frontend"
  command = "pnpm install && pnpm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# For Next.js dynamic routing on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the SPA redirect since Next.js will handle routing