[build]
  command = "npm run build"
  publish = "."   # ✅ Use "." for SSR or dynamic sites, OR leave it blank.

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
