[build]
  command = "pnpm install --frozen-lockfile && pnpm turbo run build --filter=excelidraw-frontend"
  publish = "apps/excelidraw-frontend/.next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"